name: CI

on:
  schedule:
    - cron: '30 7 1 * *'
  push:
  pull_request:

jobs:
  test:
    name: Dub Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dc:
          - dmd-latest
          - ldc-latest
          - dmd-2.095.1
          - dmd-2.094.2
          - dmd-2.093.1
          #- dmd-2.092.1 # there are linker errors on Windows for dmd 2.090 - 2.092
          #- dmd-2.091.1
          #- dmd-2.090.1
          - dmd-2.089.1 # builds fail for D versions below 2.089
          - ldc-1.25.1 # eq to dmd v2.095.1
          - ldc-1.24.0 # eq to dmd v2.094.1
          - ldc-1.23.0 # eq to dmd v2.093.1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.dc }}
        uses: dlang-community/setup-dlang@v1.1.0
        with:
          compiler: ${{ matrix.dc }}

      - name: "Posix: Run tests"
        if: runner.os != 'Windows'
        run: build/ci.sh
        env:
          TERM: xterm

      - name: "Windows: Run tests"
        if: runner.os == 'Windows'
        run: build\ci.bat
  
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.dc }}
        uses: dlang-community/setup-dlang@v1.1.0
        with:
          compiler: ${{ matrix.dc }}

      - name: "Posix: Run tests"
        if: runner.os != 'Windows'
        run: build/ci.sh
        env:
          TERM: xterm

      - uses: codecov/codecov-action@v1