name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        dc:
          - dmd-2.096.1
          - dmd-2.082.1
          - dmd-2.080.1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1.0.5
        with:
          compiler: ${{ matrix.dc }}

      - name: "Posix: Run tests"
        if: runner.os != 'Windows'
        run: dub test
        env:
          TERM: xterm

      - name: "Windows: Run tests"
        if: runner.os == 'Windows'
        run: build\ci.bat

      - uses: codecov/codecov-action@v1
